const melee = {
    NORMAL: 1,
    BLUNT: 2,
    SHARP: 4,
};

const type = {
    SMALL: 'small',
    MEDIUM: 'medium',
    LARGE: 'large',
};

const meleeWeapons = ['Knife', 'Dusters', 'Heavy Knife', 'Knuckle Knife'];

const defaultConfig = {
    rank: 100,
    dualChance: 0.25,
    priceLimit: 666,
    quartermaster: false,
    firstAidKit: true,
    melee: true,
    fixedItems: [],
    usedItems: [
        'Alert Trip Mines',
        'Ammo Box',
        'Antidote Shot',
        'Big Dynamite Bundle',
        'Blank Fire Decoys',
        'Bomb Lance',
        'Bornheim No. 3',
        'Bornheim No. 3 Extended',
        'Bornheim No. 3 Match',
        'Bornheim No3 High Velocity',
        'Bornheim No3 Incendiary',
        'Caldwell Conversion Chain Pistol',
        'Caldwell Conversion DumDum',
        'Caldwell Conversion FMJ',
        'Caldwell Conversion Pistol',
        'Caldwell Conversion Uppercut',
        'Caldwell Conversion Uppercut Explosive',
        'Caldwell Conversion Uppercut Incendiary',
        'Caldwell Pax',
        'Caldwell Pax Claw',
        'Caldwell Pax DumDum',
        'Caldwell Pax Incendiary',
        'Caldwell Rival 78',
        'Caldwell Rival 78 Flechette',
        'Caldwell Rival 78 Handcannon',
        'Caldwell Rival 78 Penny Shot',
        'Caldwell Rival 78 Slug',
        'Cavalry Saber',
        'Chaos Bomb',
        'Choke Bomb',
        'Combat Axe',
        'Concertina Bomb',
        'Concertina Trip Mines',
        'Crossbow',
        'Crossbow Explosive Bolt',
        'Crossbow Shot Bolt',
        'Crown & King Auto-5',
        'Crown & King Auto-5 Penny Shot',
        'Crown & King Auto-5 Slug',
        'Decoy Fuses',
        'Decoys',
        'Dolch 96',
        'Dolch 96 Precision',
        'Dusters',
        'Dynamite Bundle',
        'Dynamite Stick',
        'Electric Lamp',
        'Fire Bomb',
        'First Aid Kit',
        'Flare Pistol',
        'Flash Bomb',
        'Frag Bomb',
        'Fusees',
        'Hand Crossbow',
        'Hand Crossbow Chaos Bolt',
        'Hand Crossbow Choke Bolt',
        'Hand Crossbow Poison Bolt',
        'Heavy Knife',
        'Hellfire Bomb',
        'Hive Bomb',
        'Hunting Bow',
        'Hunting Bow Concertina Arrows',
        'Hunting Bow Frag Arrows',
        'Hunting Bow Poison Arrows',
        'Knife',
        'Knuckle Knife',
        'LeMat Mark II Dragonbreath',
        'LeMat Mark II FMJ',
        'LeMat Mark II Incendiary',
        'LeMat Mark II Revolver',
        'LeMat Mark II Slug',
        'LeMat Mark II Starshell',
        'Lebel 1886',
        'Lebel 1886 Aperture',
        'Lebel 1886 Incendiary',
        'Lebel 1886 Marksman',
        'Lebel 1886 Spitzer',
        'Lebel 1886 Talon',
        'Liquid Fire Bomb',
        'Machete',
        'Martini Henry IC1',
        'Martini Henry IC1 Deadeye',
        'Martini Henry IC1 Explosive',
        'Martini Henry IC1 FMJ',
        'Martini Henry IC1 Incendiary',
        'Martini Henry IC1 Marksman',
        'Martini Henry IC1 Riposte',
        'Mosin-Nagant M1891',
        'Mosin-Nagant M1891 Avtomat',
        'Mosin-Nagant M1891 Bayonet',
        'Mosin-Nagant M1891 Incendiary',
        'Mosin-Nagant M1891 Obrez',
        'Mosin-Nagant M1891 Obrez Drum',
        'Mosin-Nagant M1891 Obrez Mace',
        'Mosin-Nagant M1891 Sniper',
        'Mosin-Nagant M1891 Spitzer',
        'Nagant M1895',
        'Nagant M1895 Deadeye',
        'Nagant M1895 High Velocity',
        'Nagant M1895 Officer',
        'Nagant M1895 Officer Brawler',
        'Nagant M1895 Officer Carbine',
        'Nagant M1895 Officer Carbine Deadeye',
        'Nagant M1895 Officer High Velocity',
        'Nagant M1895 Officer Poison',
        'Nagant M1895 Poison',
        'Nagant M1895 Precision',
        'Nagant M1895 Silencer',
        'Nitro Express Rifle',
        'Nitro Express Rifle DumDum',
        'Nitro Express Rifle Explosive',
        'Poison Bomb',
        'Poison Trip Mines',
        'Quad Derringer',
        'Regeneration Shot',
        'Romero 77',
        'Romero 77 Dragonbreath',
        'Romero 77 Handcannon',
        'Romero 77 Hatchet',
        'Romero 77 Penny Shot',
        'Romero 77 Slug',
        'Romero 77 Starshell',
        'Romero 77 Talon',
        'Scottfield Model 3',
        'Scottfield Model 3 FMJ',
        'Scottfield Model 3 Incendiary',
        'Sparks LRR',
        'Sparks LRR FMJ',
        'Sparks LRR Incendiary',
        'Sparks LRR Poison',
        'Sparks LRR Silencer',
        'Sparks LRR Sniper',
        'Specter 1882',
        'Specter 1882 Bayonet',
        'Specter 1882 Compact',
        'Specter 1882 Dragonbreath',
        'Specter 1882 Flechette',
        'Specter 1882 Penny Shot',
        'Specter 1882 Slug',
        'Springfield 1866',
        'Springfield 1866 Compact',
        'Springfield 1866 Compact Deadeye',
        'Springfield 1866 Compact Striker',
        'Springfield 1866 DumDum',
        'Springfield 1866 Explosive',
        'Springfield 1866 Marksman',
        'Spyglass',
        'Stamina Shot',
        'Standard Projectile',
        'Sticky Bomb',
        'Throwing Axes',
        'Throwing Knives',
        'Vetterli 71 Karabiner',
        'Vetterli 71 Karabiner Bayonet',
        'Vetterli 71 Karabiner Deadeye',
        'Vetterli 71 Karabiner FMJ',
        'Vetterli 71 Karabiner High Velocity',
        'Vetterli 71 Karabiner Incendiary',
        'Vetterli 71 Karabiner Marksman',
        'Vetterli 71 Karabiner Silencer',
        'Vitality Shot',
        'Waxed Dynamite Stick',
        'Weak Antidote Shot',
        'Weak Regeneration Shot',
        'Weak Stamina Shot',
        'Weak Vitality Shot',
        'Winfield 1887 Terminus',
        'Winfield 1887 Terminus Dragonbreath',
        'Winfield 1887 Terminus Flechette',
        'Winfield 1887 Terminus Handcannon',
        'Winfield 1887 Terminus Penny Shot',
        'Winfield 1887 Terminus Slug',
        'Winfield M1873',
        'Winfield M1873 Aperture',
        'Winfield M1873 High Velocity',
        'Winfield M1873 Incendiary',
        'Winfield M1873 Musket Bayonet',
        'Winfield M1873 Swift',
        'Winfield M1873 Talon',
        'Winfield M1873C',
        'Winfield M1873C High Velocity',
        'Winfield M1873C Incendiary',
        'Winfield M1873C Marksman',
        'Winfield M1873C Silencer',
        'Winfield M1873C Vandal',
        'Winfield M1873C Vandal Deadeye',
        'Winfield M1873C Vandal Striker',
        'Winfield M1876 Centennial',
        'Winfield M1876 Centennial FMJ',
        'Winfield M1876 Centennial Poison',
        'Winfield M1876 Centennial Sniper',
    ],
};
