/*
 * HuntShowdownLoadoutRandomizer v1.5.2
 * by GrafKnusprig 2021/10/21
 */

const melee = {
    NORMAL: 1,
    BLUNT: 2,
    SHARP: 4,
};

const type = {
    SMALL: 'small',
    MEDIUM: 'medium',
    LARGE: 'large',
};

const defaultWeapon =
{
    name: '',
    cost: 0,
    rank: 0,
    unlock: '',
    ammo: ['', ''],
    type: type.LARGE,
    melee: melee.NORMAL,
};

const meleeWeapons = ['Knife', 'Dusters', 'Heavy Knife', 'Knuckle Knife'];

const defaultConfig = {
    rank: 100,
    dualChance: 0.25,
    priceLimit: 666,
    quartermaster: false,
    firstAidKit: true,
    melee: true,
    fixedItems: [],
    usedItems: [
        'Bomb Lance',
        'Bornheim No. 3',
        'Bornheim No. 3 Extended',
        'Bornheim No. 3 Match',
        'Bornheim No. 3 Silencer',
        'Caldwell Conversion Chain Pistol',
        'Caldwell Conversion Pistol',
        'Caldwell 92 New Army',
        'Caldwell 92 New Army Swift',
        'Caldwell Conversion Uppercut',
        'Caldwell Conversion Uppercut Precision',
        'Caldwell Conversion Uppercut Precision Deadeye',
        'Caldwell Pax',
        'Caldwell Pax Claw',
        'Caldwell Pax Trueshot',
        'Caldwell Rival 78',
        'Caldwell Rival 78 Handcannon',
        'Cavalry Saber',
        'Combat Axe',
        'Crossbow',
        'Crown & King Auto-5',
        'Dolch 96',
        'Dolch 96 Precision',
        'Dolch 96 Claw',
        'Dolch 96 Deadeye',
        'Hand Crossbow',
        'Hunting Bow',
        'LeMat Mark II Revolver',
        'LeMat Mark II Carbine',
        'LeMat Mark II Carbine Marksman',
        'LeMat Mark II UpperMat',
        'Lebel 1886',
        'Lebel 1886 Aperture',
        'Lebel 1886 Marksman',
        'Lebel 1886 Talon',
        'Machete',
        'Martini Henry IC1',
        'Martini Henry IC1 Deadeye',
        'Martini Henry IC1 Marksman',
        'Martini Henry IC1 Riposte',
        'Martini Henry IC1 Ironside',
        'Mosin-Nagant M1891',
        'Mosin-Nagant M1891 Avtomat',
        'Mosin-Nagant M1891 Bayonet',
        'Mosin-Nagant M1891 Obrez',
        'Mosin-Nagant M1891 Obrez Drum',
        'Mosin-Nagant M1891 Obrez Mace',
        'Mosin-Nagant M1891 Sniper',
        'Nagant M1895',
        'Nagant M1895 Deadeye',
        'Nagant M1895 Officer',
        'Nagant M1895 Officer Brawler',
        'Nagant M1895 Officer Carbine',
        'Nagant M1895 Officer Carbine Deadeye',
        'Nagant M1895 Precision',
        'Nagant M1895 Silencer',
        'Nitro Express Rifle',
        'Romero 77',
        'Romero 77 Handcannon',
        'Romero 77 Hatchet',
        'Romero 77 Talon',
        'Scottfield Model 3',
        'Scottfield Model 3 Brawler',
        'Scottfield Model 3 Spitfire',
        'Scottfield Model 3 Precision',
        'Scottfield Model 3 Swift',
        'Sparks LRR',
        'Sparks LRR Silencer',
        'Sparks LRR Sniper',
        'Specter 1882',
        'Specter 1882 Bayonet',
        'Specter 1882 Compact',
        'Springfield 1866',
        'Springfield 1866 Bayonet',
        'Springfield 1866 Compact',
        'Springfield 1866 Compact Deadeye',
        'Springfield 1866 Compact Striker',
        'Springfield 1866 Marksman',
        'Vetterli 71 Karabiner',
        'Vetterli 71 Karabiner Bayonet',
        'Vetterli 71 Karabiner Deadeye',
        'Vetterli 71 Karabiner Marksman',
        'Vetterli 71 Karabiner Silencer',
        'Vetterli 71 Karabiner Cyclone',
        'Winfield 1887 Terminus',
        'Winfield 1887 Terminus Handcannon',
        'Winfield M1873',
        'Winfield M1873 Aperture',
        'Winfield M1873 Musket Bayonet',
        'Winfield M1873 Swift',
        'Winfield M1873 Talon',
        'Winfield M1873C',
        'Winfield M1873C Marksman',
        'Winfield M1873C Silencer',
        'Winfield M1873C Vandal',
        'Winfield M1873C Vandal Deadeye',
        'Winfield M1873C Vandal Striker',
        'Winfield M1876 Centennial',
        'Winfield M1876 Centennial Sniper',
        'Winfield M1876 Centennial Shorty',
        'Winfield M1876 Centennial Shorty Silencer',
        'Winfield 1893 Slate',
        'Berthier Mle 1892',
        'Berthier Mle 1892 Deadeye',
        'Berthier Mle 1892 Riposte',
        'Berthier Mle 1892 Marksman',
        'Sparks Pistol',
        'Romero 77 Alamo',
        'Springfield M1892 Krag',
        'Springfield M1892 Krag Bayonet',
        'Springfield M1892 Krag Sniper',
        'Baseball Bat',
        'Drilling',
        'Drilling Handcannon',
        'Drilling Hatchet',
        'Katana',
        'Railroad Hammer',
        'Springfield M1892 Krag',
        'Springfield M1892 Krag Bayonet',
        'Springfield M1892 Krag Sniper',
        'Alert Trip Mines',
        'Blank Fire Decoys',
        'Choke Bomb',
        'Concertina Trip Mines',
        'Decoy Fuses',
        'Decoys',
        'Dusters',
        'Electric Lamp',
        'First Aid Kit',
        'Flare Pistol',
        'Fusees',
        'Heavy Knife',
        'Knife',
        'Knuckle Knife',
        'Poison Trip Mines',
        'Quad Derringer',
        'Derringer Pennyshot',
        'Spyglass',
        'Throwing Axes',
        'Throwing Knives',
        'Ammo Box',
        'Antidote Shot',
        'Big Dynamite Bundle',
        'Chaos Bomb',
        'Concertina Bomb',
        'Dynamite Bundle',
        'Dynamite Stick',
        'Fire Bomb',
        'Flash Bomb',
        'Frag Bomb',
        'Hellfire Bomb',
        'Hive Bomb',
        'Liquid Fire Bomb',
        'Poison Bomb',
        'Regeneration Shot',
        'Stalker Beetle',
        'Choke Beetle',
        'Fire Beetle',
        'Stamina Shot',
        'Sticky Bomb',
        'Vitality Shot',
        'Waxed Dynamite Stick',
        'Weak Antidote Shot',
        'Weak Regeneration Shot',
        'Weak Stamina Shot',
        'Weak Vitality Shot',
        'Medical Pack',
        'Tool Box',
        'Bornheim No3 High Velocity',
        'Bornheim No3 Incendiary',
        'Caldwell Conversion DumDum',
        'Caldwell Conversion FMJ',
        'Caldwell Conversion Uppercut Explosive',
        'Caldwell Conversion Uppercut Incendiary',
        'Caldwell Conversion Uppercut FMJ',
        'Caldwell Pax DumDum',
        'Caldwell Pax Incendiary',
        'Caldwell Pax FMJ',
        'Caldwell Pax Poison',
        'Caldwell Rival 78 Flechette',
        'Caldwell Rival 78 Penny Shot',
        'Caldwell Rival 78 Slug',
        'Crossbow Explosive Bolt',
        'Crossbow Shot Bolt',
        'Crown & King Auto-5 Penny Shot',
        'Crown & King Auto-5 Slug',
        'Hand Crossbow Chaos Bolt',
        'Hand Crossbow Choke Bolt',
        'Hand Crossbow Poison Bolt',
        'Hand Crossbow Dragon Bolt',
        'Hunting Bow Concertina Arrows',
        'Hunting Bow Frag Arrows',
        'Hunting Bow Poison Arrows',
        'LeMat Mark II Dragonbreath',
        'LeMat Mark II FMJ',
        'LeMat Mark II Incendiary',
        'LeMat Mark II Slug',
        'LeMat Mark II Starshell',
        'Lebel 1886 Incendiary',
        'Lebel 1886 Spitzer',
        'Martini Henry IC1 Explosive',
        'Martini Henry IC1 FMJ',
        'Martini Henry IC1 Incendiary',
        'Mosin-Nagant M1891 Incendiary',
        'Mosin-Nagant M1891 Spitzer',
        'Nagant M1895 High Velocity',
        'Nagant M1895 Officer High Velocity',
        'Nagant M1895 Officer Poison',
        'Nagant M1895 Officer DumDum',
        'Nagant M1895 Poison',
        'Nagant M1895 Dumdum',
        'Nitro Express Rifle Shredder',
        'Nitro Express Rifle Explosive',
        'Romero 77 Dragonbreath',
        'Romero 77 Penny Shot',
        'Romero 77 Slug',
        'Romero 77 Starshell',
        'Romero 77 Alamo Dragonbreath',
        'Romero 77 Alamo Penny Shot',
        'Romero 77 Alamo Slug',
        'Romero 77 Alamo Starshell',
        'Scottfield Model 3 FMJ',
        'Scottfield Model 3 Incendiary',
        'Scottfield Model 3 DumDum',
        'Scottfield Model 3 High Velocity',
        'Sparks LRR FMJ',
        'Sparks LRR Incendiary',
        'Sparks LRR Poison',
        'Specter 1882 Dragonbreath',
        'Specter 1882 Flechette',
        'Specter 1882 Penny Shot',
        'Specter 1882 Slug',
        'Springfield 1866 DumDum',
        'Springfield 1866 Explosive',
        'Springfield 1866 Poison',
        'Springfield 1866 High Velocity',
        'Standard Projectile',
        'Vetterli 71 Karabiner FMJ',
        'Vetterli 71 Karabiner High Velocity',
        'Vetterli 71 Karabiner Incendiary',
        'Winfield 1887 Terminus Dragonbreath',
        'Winfield 1887 Terminus Flechette',
        'Winfield 1887 Terminus Penny Shot',
        'Winfield 1887 Terminus Slug',
        'Winfield M1873 High Velocity',
        'Winfield M1873 Incendiary',
        'Winfield M1873 FMJ',
        'Winfield M1873C High Velocity',
        'Winfield M1873C Incendiary',
        'Winfield M1873C FMJ',
        'Winfield M1876 Centennial FMJ',
        'Winfield M1876 Centennial Poison',
        'Winfield M1876 Centennial High Velocity',
        'Winfield M1876 Centennial DumDum',
        'Winfield 1893 Slate Penny Shot',
        'Winfield 1893 Slate Slug',
        'Berthier Mle 1892 Incendiary',
        'Berthier Mle 1892 Spitzer',
        'Caldwell 92 New Army DumDum',
        'Caldwell 92 New Army FMJ',
        'Springfield M1892 Krag Incendiary',
        'Springfield M1892 Krag FMJ',
        'Bomb Lance Dragon Breath',
        'Bomb Lance Steel Ball',
        'Bomb Lance Waxed Frag Charge',
        'Drilling FMJ',
        'Drilling DumDum',
        'Drilling Flechette',
        'Drilling Slug',
        'Drilling Penny Shot',
        'LeMat Mark II UpperMat FMJ',
        'LeMat Mark II UpperMat Poison',
        'LeMat Mark II UpperMat Starshell',
        'LeMat Mark II UpperMat Dragonbreath',
        'LeMat Mark II UpperMat Slug',
        'Springfield M1892 Krag FMJ',
        'Springfield M1892 Krag Incendiary',
        'Dolch 96 DumDum',
        'Dolch 96 FMJ',
    ],
};
