/*
 * HuntShowdownLoadoutRandomizer v1.5.2
 * by GrafKnusprig 2021/10/21
 */

const weapons = [
    {
        name: 'Bomb Lance',
        cost: 199,
        rank: 78,
        type: type.LARGE,
        melee: melee.SHARP,
    },
    {
        name: 'Bornheim No. 3',
        cost: 146,
        rank: 35,
        ammo: ['Bornheim No3 Incendiary', 'Bornheim No3 High Velocity'],
        type: type.SMALL,
        pair: true,
        melee: melee.NORMAL,
    },
    {
        name: 'Bornheim No. 3 Extended',
        cost: 203,
        unlock: 'Bornheim No. 3',
        ammo: ['Bornheim No3 Incendiary', 'Bornheim No3 High Velocity'],
        type: type.SMALL,
        pair: true,
        melee: melee.NORMAL,
    },
    {
        name: 'Bornheim No. 3 Match',
        cost: 180,
        unlock: 'Bornheim No. 3 Extended',
        ammo: ['Bornheim No3 Incendiary', 'Bornheim No3 High Velocity'],
        type: type.MEDIUM,
        melee: melee.NORMAL,
    },
    {
        name: 'Caldwell Conversion Chain Pistol',
        cost: 84,
        unlock: 'Caldwell Conversion Pistol',
        ammo: ['Caldwell Conversion DumDum', 'Caldwell Conversion FMJ'],
        type: type.SMALL,
        pair: true,
        melee: melee.NORMAL,
    },
    {
        name: 'Caldwell Conversion Pistol',
        cost: 55,
        rank: 18,
        ammo: ['Caldwell Conversion DumDum', 'Caldwell Conversion FMJ'],
        type: type.SMALL,
        pair: true,
        melee: melee.NORMAL,
    },
    {
        name: 'Caldwell 92 New Army',
        cost: 90,
        rank: 12,
        ammo: ['Caldwell 92 New Army DumDum', 'Caldwell 92 New Army FMJ'],
        type: type.SMALL,
        pair: true,
        melee: melee.NORMAL,
    },
    {
        name: 'Caldwell Conversion Uppercut',
        cost: 414,
        unlock: 'Caldwell Conversion Chain Pistol',
        ammo: ['Caldwell Conversion Uppercut Incendiary', 'Caldwell Conversion Uppercut Explosive'],
        type: type.SMALL,
        pair: true,
        melee: melee.NORMAL,
    },
    {
        name: 'Caldwell Pax',
        cost: 80,
        rank: 30,
        ammo: ['Caldwell Pax Incendiary', 'Caldwell Pax DumDum'],
        type: type.SMALL,
        pair: true,
        melee: melee.NORMAL,
    },
    {
        name: 'Caldwell Pax Claw',
        cost: 105,
        unlock: 'Caldwell Pax',
        ammo: ['Caldwell Pax Incendiary', 'Caldwell Pax DumDum'],
        type: type.SMALL,
        pair: true,
        melee: melee.SHARP,
    },
    {
        name: 'Caldwell Rival 78',
        cost: 150,
        rank: 16,
        ammo: ['Caldwell Rival 78 Flechette', 'Caldwell Rival 78 Slug', 'Caldwell Rival 78 Penny Shot'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Caldwell Rival 78 Handcannon',
        cost: 125,
        unlock: 'Caldwell Rival 78',
        ammo: ['Caldwell Rival 78 Flechette', 'Caldwell Rival 78 Slug', 'Caldwell Rival 78 Penny Shot'],
        type: type.MEDIUM,
        melee: melee.NORMAL,
    },
    {
        name: 'Cavalry Saber',
        cost: 60,
        rank: 42,
        type: type.SMALL,
        pair: false,
        melee: melee.SHARP,
    },
    {
        name: 'Combat Axe',
        cost: 15,
        rank: 1,
        type: type.MEDIUM,
        melee: melee.SHARP,
    },
    {
        name: 'Crossbow',
        cost: 50,
        unlock: 'Hand Crossbow Poison Bolt',
        ammo: [
            ['Crossbow Shot Bolt', 'Crossbow Explosive Bolt'],
            ['Crossbow Shot Bolt', 'Crossbow Explosive Bolt'],
        ],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Crown & King Auto-5',
        cost: 600,
        rank: 82,
        ammo: ['Crown & King Auto-5 Penny Shot', 'Crown & King Auto-5 Slug'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Dolch 96',
        cost: 750,
        rank: 71,
        type: type.SMALL,
        pair: true,
        melee: melee.NORMAL,
    },
    {
        name: 'Dolch 96 Precision',
        cost: 790,
        unlock: 'Dolch 96',
        type: type.MEDIUM,
        melee: melee.NORMAL,
    },
    {
        name: 'Hand Crossbow',
        cost: 30,
        rank: 21,
        ammo: [
            ['Hand Crossbow Choke Bolt', 'Hand Crossbow Chaos Bolt', 'Hand Crossbow Poison Bolt'],
            ['Hand Crossbow Choke Bolt', 'Hand Crossbow Chaos Bolt', 'Hand Crossbow Poison Bolt'],
        ],
        type: type.SMALL,
        melee: melee.NORMAL,
    },
    {
        name: 'Hunting Bow',
        cost: 57,
        rank: 54,
        ammo: [
            ['Hunting Bow Poison Arrows', 'Hunting Bow Concertina Arrows', 'Hunting Bow Frag Arrows'],
            ['Hunting Bow Poison Arrows', 'Hunting Bow Concertina Arrows', 'Hunting Bow Frag Arrows'],
        ],
        type: type.MEDIUM,
        melee: melee.NORMAL,
    },
    {
        name: 'LeMat Mark II Revolver',
        cost: 95,
        rank: 46,
        ammo: [
            ['LeMat Mark II Incendiary', 'LeMat Mark II FMJ'],
            ['LeMat Mark II Starshell', 'LeMat Mark II Dragonbreath', 'LeMat Mark II Slug'],
        ],
        type: type.SMALL,
        pair: true,
        melee: melee.NORMAL,
    },
    {
        name: 'Lebel 1886',
        cost: 397,
        rank: 52,
        ammo: ['Lebel 1886 Incendiary', 'Lebel 1886 Spitzer'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Lebel 1886 Aperture',
        cost: 425,
        unlock: 'Lebel 1886 Incendiary',
        ammo: ['Lebel 1886 Incendiary', 'Lebel 1886 Spitzer'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Lebel 1886 Marksman',
        cost: 607,
        unlock: 'Lebel 1886 Talon',
        ammo: ['Lebel 1886 Incendiary', 'Lebel 1886 Spitzer'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Lebel 1886 Talon',
        cost: 422,
        unlock: 'Lebel 1886 Aperture',
        ammo: ['Lebel 1886 Incendiary', 'Lebel 1886 Spitzer'],
        type: type.LARGE,
        melee: melee.SHARP,
    },
    {
        name: 'Machete',
        cost: 18,
        rank: 1,
        type: type.SMALL,
        pair: false,
        melee: melee.SHARP,
    },
    {
        name: 'Martini Henry IC1',
        cost: 122,
        rank: 9,
        ammo: [
            ['Martini Henry IC1 Incendiary', 'Martini Henry IC1 FMJ', 'Martini Henry IC1 Explosive'],
            ['Martini Henry IC1 Incendiary', 'Martini Henry IC1 FMJ', 'Martini Henry IC1 Explosive'],
        ],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Martini Henry IC1 Deadeye',
        cost: 145,
        unlock: 'Martini Henry IC1 Incendiary',
        ammo: [
            ['Martini Henry IC1 Incendiary', 'Martini Henry IC1 FMJ', 'Martini Henry IC1 Explosive'],
            ['Martini Henry IC1 Incendiary', 'Martini Henry IC1 FMJ', 'Martini Henry IC1 Explosive'],
        ],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Martini Henry IC1 Marksman',
        cost: 173,
        unlock: 'Martini Henry IC1 Riposte',
        ammo: [
            ['Martini Henry IC1 Incendiary', 'Martini Henry IC1 FMJ', 'Martini Henry IC1 Explosive'],
            ['Martini Henry IC1 Incendiary', 'Martini Henry IC1 FMJ', 'Martini Henry IC1 Explosive'],
        ],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Martini Henry IC1 Riposte',
        cost: 164,
        unlock: 'Martini Henry IC1 FMJ',
        ammo: [
            ['Martini Henry IC1 Incendiary', 'Martini Henry IC1 FMJ', 'Martini Henry IC1 Explosive'],
            ['Martini Henry IC1 Incendiary', 'Martini Henry IC1 FMJ', 'Martini Henry IC1 Explosive'],
        ],
        type: type.LARGE,
        melee: melee.SHARP,
    },
    {
        name: 'Mosin-Nagant M1891',
        cost: 490,
        rank: 75,
        ammo: ['Mosin-Nagant M1891 Incendiary', 'Mosin-Nagant M1891 Spitzer'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Mosin-Nagant M1891 Avtomat',
        cost: 1250,
        unlock: 'Mosin-Nagant M1891 Sniper',
        ammo: ['Mosin-Nagant M1891 Incendiary', 'Mosin-Nagant M1891 Spitzer'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Mosin-Nagant M1891 Bayonet',
        cost: 540,
        unlock: 'Mosin-Nagant M1891 Obrez',
        ammo: ['Mosin-Nagant M1891 Incendiary', 'Mosin-Nagant M1891 Spitzer'],
        type: type.LARGE,
        melee: melee.SHARP,
    },
    {
        name: 'Mosin-Nagant M1891 Obrez',
        cost: 290,
        unlock: 'Mosin-Nagant M1891',
        ammo: ['Mosin-Nagant M1891 Incendiary', 'Mosin-Nagant M1891 Spitzer'],
        type: type.MEDIUM,
        melee: melee.NORMAL,
    },
    {
        name: 'Mosin-Nagant M1891 Obrez Drum',
        cost: 350,
        unlock: 'Mosin-Nagant M1891 Sniper',
        ammo: ['Mosin-Nagant M1891 Incendiary', 'Mosin-Nagant M1891 Spitzer'],
        type: type.MEDIUM,
        melee: melee.NORMAL,
    },
    {
        name: 'Mosin-Nagant M1891 Obrez Mace',
        cost: 310,
        unlock: 'Mosin-Nagant M1891 Bayonet',
        ammo: ['Mosin-Nagant M1891 Incendiary', 'Mosin-Nagant M1891 Spitzer'],
        type: type.MEDIUM,
        melee: melee.BLUNT,
    },
    {
        name: 'Mosin-Nagant M1891 Sniper',
        cost: 730,
        unlock: 'Mosin-Nagant M1891 Obrez Mace',
        ammo: ['Mosin-Nagant M1891 Incendiary', 'Mosin-Nagant M1891 Spitzer'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Nagant M1895',
        cost: 24,
        rank: 1,
        ammo: ['Nagant M1895 High Velocity', 'Nagant M1895 Poison'],
        type: type.SMALL,
        pair: true,
        melee: melee.NORMAL,
    },
    {
        name: 'Nagant M1895 Deadeye',
        cost: 42,
        unlock: 'Nagant M1895 Silencer',
        ammo: ['Nagant M1895 High Velocity', 'Nagant M1895 Poison'],
        type: type.MEDIUM,
        melee: melee.NORMAL,
    },
    {
        name: 'Nagant M1895 Officer',
        cost: 96,
        rank: 56,
        ammo: ['Nagant M1895 Officer High Velocity', 'Nagant M1895 Officer Poison'],
        type: type.SMALL,
        pair: true,
        melee: melee.NORMAL,
    },
    {
        name: 'Nagant M1895 Officer Brawler',
        cost: 110,
        unlock: 'Nagant M1895 Officer',
        ammo: ['Nagant M1895 Officer High Velocity', 'Nagant M1895 Officer Poison'],
        type: type.SMALL,
        pair: true,
        melee: melee.BLUNT,
    },
    {
        name: 'Nagant M1895 Officer Carbine',
        cost: 155,
        unlock: 'Nagant M1895 Officer Brawler',
        ammo: ['Nagant M1895 Officer High Velocity', 'Nagant M1895 Officer Poison'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Nagant M1895 Officer Carbine Deadeye',
        cost: 211,
        unlock: 'Nagant M1895 Officer Carbine',
        ammo: ['Nagant M1895 Officer High Velocity', 'Nagant M1895 Officer Poison'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Nagant M1895 Precision',
        cost: 29,
        unlock: 'Nagant M1895',
        ammo: ['Nagant M1895 High Velocity', 'Nagant M1895 Poison'],
        type: type.MEDIUM,
        melee: melee.NORMAL,
    },
    {
        name: 'Nagant M1895 Silencer',
        cost: 93,
        unlock: 'Nagant M1895 Precision',
        ammo: ['Nagant M1895 High Velocity', 'Nagant M1895 Poison'],
        type: type.SMALL,
        pair: true,
        melee: melee.NORMAL,
    },
    {
        name: 'Nitro Express Rifle',
        cost: 1015,
        rank: 90,
        ammo: ['Nitro Express Rifle Shredder', 'Nitro Express Rifle Explosive'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Romero 77',
        cost: 66,
        rank: 1,
        ammo: [
            ['Romero 77 Starshell', 'Romero 77 Dragonbreath', 'Romero 77 Penny Shot', 'Romero 77 Slug'],
            ['Romero 77 Starshell', 'Romero 77 Dragonbreath', 'Romero 77 Penny Shot', 'Romero 77 Slug'],
        ],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Romero 77 Handcannon',
        cost: 46,
        unlock: 'Romero 77',
        ammo: [
            ['Romero 77 Starshell', 'Romero 77 Dragonbreath', 'Romero 77 Penny Shot', 'Romero 77 Slug'],
            ['Romero 77 Starshell', 'Romero 77 Dragonbreath', 'Romero 77 Penny Shot', 'Romero 77 Slug'],
        ],
        type: type.MEDIUM,
        melee: melee.NORMAL,
    },
    {
        name: 'Romero 77 Hatchet',
        cost: 82,
        unlock: 'Romero 77 Penny Shot',
        ammo: [
            ['Romero 77 Starshell', 'Romero 77 Dragonbreath', 'Romero 77 Penny Shot', 'Romero 77 Slug'],
            ['Romero 77 Starshell', 'Romero 77 Dragonbreath', 'Romero 77 Penny Shot', 'Romero 77 Slug'],
        ],
        type: type.MEDIUM,
        melee: melee.SHARP,
    },
    {
        name: 'Romero 77 Talon',
        cost: 84,
        unlock: 'Romero 77 Dragonbreath',
        ammo: [
            ['Romero 77 Starshell', 'Romero 77 Dragonbreath', 'Romero 77 Penny Shot', 'Romero 77 Slug'],
            ['Romero 77 Starshell', 'Romero 77 Dragonbreath', 'Romero 77 Penny Shot', 'Romero 77 Slug'],
        ],
        type: type.LARGE,
        melee: melee.SHARP,
    },
    {
        name: 'Scottfield Model 3',
        cost: 77,
        rank: 1,
        pair: true,
        ammo: ['Scottfield Model 3 Incendiary', 'Scottfield Model 3 FMJ'],
        type: type.SMALL,
        melee: melee.NORMAL,
    },
    {
        name: 'Scottfield Model 3 Brawler',
        cost: 92,
        unlock: 'Scottfield Model 3 Incendiary',
        pair: true,
        ammo: ['Scottfield Model 3 Incendiary', 'Scottfield Model 3 FMJ'],
        type: type.SMALL,
        melee: melee.BLUNT,
    },
    {
        name: 'Scottfield Model 3 Spitfire',
        cost: 108,
        unlock: 'Scottfield Model 3 FMJ',
        pair: true,
        ammo: ['Scottfield Model 3 Incendiary', 'Scottfield Model 3 FMJ'],
        type: type.SMALL,
        melee: melee.NORMAL,
    },
    {
        name: 'Scottfield Model 3 Precision',
        cost: 85,
        unlock: 'Scottfield Model 3 Spitfire',
        ammo: ['Scottfield Model 3 Incendiary', 'Scottfield Model 3 FMJ'],
        type: type.MEDIUM,
        melee: melee.NORMAL,
    },
    {
        name: 'Scottfield Model 3 Swift',
        cost: 95,
        unlock: 'Scottfield Model 3 Precision',
        pair: true,
        ammo: ['Scottfield Model 3 Incendiary', 'Scottfield Model 3 FMJ'],
        type: type.SMALL,
        melee: melee.NORMAL,
    },
    {
        name: 'Sparks LRR',
        cost: 130,
        rank: 32,
        ammo: [
            ['Sparks LRR Incendiary', 'Sparks LRR Poison', 'Sparks LRR FMJ'],
            ['Sparks LRR Incendiary', 'Sparks LRR Poison', 'Sparks LRR FMJ'],
        ],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Sparks LRR Silencer',
        cost: 150,
        unlock: 'Sparks Pistol',
        ammo: [
            ['Sparks LRR Incendiary', 'Sparks LRR Poison', 'Sparks LRR FMJ'],
            ['Sparks LRR Incendiary', 'Sparks LRR Poison', 'Sparks LRR FMJ'],
        ],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Sparks LRR Sniper',
        cost: 199,
        unlock: 'Sparks LRR Poison',
        ammo: [
            ['Sparks LRR Incendiary', 'Sparks LRR Poison', 'Sparks LRR FMJ'],
            ['Sparks LRR Incendiary', 'Sparks LRR Poison', 'Sparks LRR FMJ'],
        ],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Specter 1882',
        cost: 188,
        rank: 38,
        ammo: ['Specter 1882 Dragonbreath', 'Specter 1882 Slug', 'Specter 1882 Flechette', 'Specter 1882 Penny Shot'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Specter 1882 Bayonet',
        cost: 223,
        unlock: 'Specter 1882 Compact',
        ammo: ['Specter 1882 Dragonbreath', 'Specter 1882 Slug', 'Specter 1882 Flechette', 'Specter 1882 Penny Shot'],
        type: type.LARGE,
        melee: melee.SHARP,
    },
    {
        name: 'Specter 1882 Compact',
        cost: 164,
        unlock: 'Specter 1882',
        ammo: ['Specter 1882 Dragonbreath', 'Specter 1882 Slug', 'Specter 1882 Flechette', 'Specter 1882 Penny Shot'],
        type: type.MEDIUM,
        melee: melee.NORMAL,
    },
    {
        name: 'Springfield 1866',
        cost: 38,
        rank: 1,
        ammo: [
            ['Springfield 1866 DumDum', 'Springfield 1866 Explosive'],
            ['Springfield 1866 DumDum', 'Springfield 1866 Explosive'],
        ],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Springfield 1866 Compact',
        cost: 33,
        unlock: 'Springfield 1866 Marksman',
        ammo: [
            ['Springfield 1866 DumDum', 'Springfield 1866 Explosive'],
            ['Springfield 1866 DumDum', 'Springfield 1866 Explosive'],
        ],
        type: type.MEDIUM,
        melee: melee.NORMAL,
    },
    {
        name: 'Springfield 1866 Compact Deadeye',
        cost: 46,
        unlock: 'Springfield 1866 Compact Striker',
        ammo: [
            ['Springfield 1866 DumDum', 'Springfield 1866 Explosive'],
            ['Springfield 1866 DumDum', 'Springfield 1866 Explosive'],
        ],
        type: type.MEDIUM,
        melee: melee.NORMAL,
    },
    {
        name: 'Springfield 1866 Compact Striker',
        cost: 56,
        unlock: 'Springfield 1866 Compact',
        ammo: [
            ['Springfield 1866 DumDum', 'Springfield 1866 Explosive'],
            ['Springfield 1866 DumDum', 'Springfield 1866 Explosive'],
        ],
        type: type.MEDIUM,
        melee: melee.SHARP,
    },
    {
        name: 'Springfield 1866 Marksman',
        cost: 73,
        unlock: 'Springfield 1866',
        ammo: [
            ['Springfield 1866 DumDum', 'Springfield 1866 Explosive'],
            ['Springfield 1866 DumDum', 'Springfield 1866 Explosive'],
        ],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Vetterli 71 Karabiner',
        cost: 105,
        rank: 14,
        ammo: ['Vetterli 71 Karabiner Incendiary', 'Vetterli 71 Karabiner FMJ', 'Vetterli 71 Karabiner High Velocity'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Vetterli 71 Karabiner Bayonet',
        cost: 155,
        unlock: 'Vetterli 71 Karabiner FMJ',
        ammo: ['Vetterli 71 Karabiner Incendiary', 'Vetterli 71 Karabiner FMJ', 'Vetterli 71 Karabiner High Velocity'],
        type: type.LARGE,
        melee: melee.SHARP,
    },
    {
        name: 'Vetterli 71 Karabiner Deadeye',
        cost: 130,
        unlock: 'Vetterli 71 Karabiner',
        ammo: ['Vetterli 71 Karabiner Incendiary', 'Vetterli 71 Karabiner FMJ', 'Vetterli 71 Karabiner High Velocity'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Vetterli 71 Karabiner Marksman',
        cost: 190,
        unlock: 'Vetterli 71 Karabiner Incendiary',
        ammo: ['Vetterli 71 Karabiner Incendiary', 'Vetterli 71 Karabiner FMJ', 'Vetterli 71 Karabiner High Velocity'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Vetterli 71 Karabiner Silencer',
        cost: 150,
        unlock: 'Vetterli 71 Karabiner Bayonet',
        ammo: ['Vetterli 71 Karabiner Incendiary', 'Vetterli 71 Karabiner FMJ', 'Vetterli 71 Karabiner High Velocity'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Winfield 1887 Terminus',
        cost: 238,
        rank: 4,
        ammo: ['Winfield 1887 Terminus Flechette', 'Winfield 1887 Terminus Penny Shot', 'Winfield 1887 Terminus Slug'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Winfield 1887 Terminus Handcannon',
        cost: 218,
        unlock: 'Winfield 1887 Terminus',
        ammo: ['Winfield 1887 Terminus Flechette', 'Winfield 1887 Terminus Penny Shot', 'Winfield 1887 Terminus Slug'],
        type: type.MEDIUM,
        melee: melee.NORMAL,
    },
    {
        name: 'Winfield M1873',
        cost: 75,
        rank: 27,
        ammo: ['Winfield M1873 Incendiary', 'Winfield M1873 High Velocity'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Winfield M1873 Aperture',
        cost: 80,
        unlock: 'Winfield M1873',
        ammo: ['Winfield M1873 Incendiary', 'Winfield M1873 High Velocity'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Winfield M1873 Musket Bayonet',
        cost: 137,
        unlock: 'Winfield M1873 FMJ',
        ammo: ['Winfield M1873 Incendiary', 'Winfield M1873 High Velocity'],
        type: type.LARGE,
        melee: melee.SHARP,
    },
    {
        name: 'Winfield M1873 Swift',
        cost: 128,
        unlock: 'Winfield M1873 High Velocity',
        ammo: ['Winfield M1873 Incendiary', 'Winfield M1873 High Velocity'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Winfield M1873 Talon',
        cost: 100,
        unlock: 'Winfield M1873 Aperture',
        ammo: ['Winfield M1873 Incendiary', 'Winfield M1873 High Velocity'],
        type: type.LARGE,
        melee: melee.SHARP,
    },
    {
        name: 'Winfield M1873C',
        cost: 41,
        rank: 1,
        ammo: ['Winfield M1873C Incendiary', 'Winfield M1873C High Velocity'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Winfield M1873C Marksman',
        cost: 56,
        unlock: 'Winfield M1873C Silencer',
        ammo: ['Winfield M1873C Incendiary', 'Winfield M1873C High Velocity'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Winfield M1873C Silencer',
        cost: 55,
        unlock: 'Winfield M1873C',
        ammo: ['Winfield M1873C Incendiary', 'Winfield M1873C High Velocity'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Winfield M1873C Vandal',
        cost: 35,
        unlock: 'Winfield M1873C Marksman',
        ammo: ['Winfield M1873C Incendiary', 'Winfield M1873C High Velocity'],
        type: type.MEDIUM,
        melee: melee.NORMAL,
    },
    {
        name: 'Winfield M1873C Vandal Deadeye',
        cost: 45,
        unlock: 'Winfield M1873C FMJ',
        ammo: ['Winfield M1873C Incendiary', 'Winfield M1873C High Velocity'],
        type: type.MEDIUM,
        melee: melee.NORMAL,
    },
    {
        name: 'Winfield M1873C Vandal Striker',
        cost: 39,
        unlock: 'Winfield M1873C Vandal',
        ammo: ['Winfield M1873C Incendiary', 'Winfield M1873C High Velocity'],
        type: type.MEDIUM,
        melee: melee.SHARP,
    },
    {
        name: 'Winfield M1876 Centennial',
        cost: 157,
        rank: 24,
        ammo: ['Winfield M1876 Centennial Poison', 'Winfield M1876 Centennial FMJ'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Winfield M1876 Centennial Sniper',
        cost: 229,
        unlock: 'Winfield M1876 Centennial FMJ',
        ammo: ['Winfield M1876 Centennial Poison', 'Winfield M1876 Centennial FMJ'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Winfield 1893 Slate',
        cost: 333,
        rank: 65,
        ammo: ['Winfield 1893 Slate Slug', 'Winfield 1893 Slate Penny Shot'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Berthier Mle 1892',
        cost: 356,
        rank: 48,
        ammo: ['Berthier Mle 1892 Incendiary', 'Berthier Mle 1892 Spitzer'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Berthier Mle 1892 Deadeye',
        cost: 388,
        unlock: 'Berthier Mle 1892 Riposte',
        ammo: ['Berthier Mle 1892 Incendiary', 'Berthier Mle 1892 Spitzer'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
    {
        name: 'Berthier Mle 1892 Riposte',
        cost: 370,
        unlock: 'Berthier Mle 1892 Incendiary',
        ammo: ['Berthier Mle 1892 Incendiary', 'Berthier Mle 1892 Spitzer'],
        type: type.LARGE,
        melee: melee.SHARP,
    },
	{
        name: 'Sparks Pistol',
        cost: 155,
        unlock: 'Sparks LRR Incendiary',
        ammo: ['Sparks LRR Incendiary', 'Sparks LRR FMJ', 'Sparks LRR Poison'],
        pair: true,
        type: type.SMALL,
        melee: melee.NORMAL,
    },
    {
        name: 'Romero 77 Alamo',
        cost: 98,
        unlock: 'Romero 77 Hatchet',
        ammo: ['Romero 77 Alamo Starshell', 'Romero 77 Alamo Dragonbreath', 'Romero 77 Alamo Penny Shot', 'Romero 77 Alamo Slug'],
        type: type.LARGE,
        melee: melee.NORMAL,
    },
];

const tools = [
    { name: 'Alert Trip Mines', cost: 30, unlock: 'Decoys', melee: melee.NORMAL },
    { name: 'Blank Fire Decoys', cost: 45, unlock: 'Chaos Bomb', melee: melee.NORMAL },
    { name: 'Choke Bomb', cost: 25, rank: 1, melee: melee.NORMAL },
    { name: 'Concertina Trip Mines', cost: 90, rank: 40, melee: melee.NORMAL },
    { name: 'Decoy Fuses', cost: 30, unlock: 'Blank Fire Decoys', melee: melee.NORMAL },
    { name: 'Decoys', cost: 6, rank: 1, melee: melee.NORMAL },
    { name: 'Dusters', cost: 15, rank: 1, melee: melee.BLUNT },
    { name: 'Electric Lamp', cost: 5, rank: 1, melee: melee.NORMAL },
    { name: 'First Aid Kit', cost: 30, rank: 1, melee: melee.NORMAL },
    { name: 'Flare Pistol', cost: 36, unlock: 'Fusees', melee: melee.NORMAL },
    { name: 'Fusees', cost: 10, unlock: 'Electric Lamp', melee: melee.NORMAL },
    { name: 'Heavy Knife', cost: 20, unlock: 'Throwing Knives', melee: melee.SHARP },
    { name: 'Knife', cost: 30, rank: 1, melee: melee.SHARP },
    { name: 'Knuckle Knife', cost: 15, unlock: 'Dusters', melee: melee.BLUNT | melee.SHARP },
    { name: 'Poison Trip Mines', cost: 30, unlock: 'Hive Bomb', melee: melee.NORMAL },
    { name: 'Quad Derringer', cost: 30, rank: 80, melee: melee.NORMAL },
    { name: 'Spyglass', cost: 8, rank: 1, melee: melee.NORMAL },
    { name: 'Throwing Axes', cost: 30, unlock: 'Heavy Knife', melee: melee.SHARP },
    { name: 'Throwing Knives', cost: 40, unlock: 'Knife', melee: melee.SHARP },
];

const consumables = [
    { name: 'Ammo Box', cost: 65, rank: 74 },
    { name: 'Antidote Shot', cost: 55, unlock: 'Weak Antidote Shot' },
    { name: 'Big Dynamite Bundle', cost: 110, unlock: 'Frag Bomb' },
    { name: 'Chaos Bomb', cost: 15, unlock: 'Alert Trip Mines' },
    { name: 'Concertina Bomb', cost: 48, unlock: 'Flash Bomb' },
    { name: 'Dynamite Bundle', cost: 75, unlock: 'Sticky Bomb' },
    { name: 'Dynamite Stick', cost: 18, rank: 6 },
    { name: 'Fire Bomb', cost: 30, rank: 1 },
    { name: 'Flash Bomb', cost: 47, unlock: 'Concertina Trip Mines' },
    { name: 'Frag Bomb', cost: 103, unlock: 'Dynamite Bundle' },
    { name: 'Hellfire Bomb', cost: 70, unlock: 'Liquid Fire Bomb' },
    { name: 'Hive Bomb', cost: 40, unlock: 'Antidote Shot' },
    { name: 'Liquid Fire Bomb', cost: 35, unlock: 'Fire Bomb' },
    { name: 'Poison Bomb', cost: 25, rank: 48 },
    { name: 'Regeneration Shot', cost: 85, unlock: 'Stamina Shot' },
    { name: 'Stalker Beetle', cost: 45, rank: 15 },
    { name: 'Stamina Shot', cost: 100, unlock: 'Vitality Shot' },
    { name: 'Sticky Bomb', cost: 64, unlock: 'Waxed Dynamite Stick' },
    { name: 'Vitality Shot', cost: 85, unlock: 'Weak Regeneration Shot' },
    { name: 'Waxed Dynamite Stick', cost: 24, unlock: 'Dynamite Stick' },
    { name: 'Weak Antidote Shot', cost: 30, rank: 2 },
    { name: 'Weak Regeneration Shot', cost: 20, unlock: 'Weak Stamina Shot' },
    { name: 'Weak Stamina Shot', cost: 60, unlock: 'Weak Vitality Shot' },
    { name: 'Weak Vitality Shot', cost: 20, rank: 1 },
];

const ammunition = [
    { name: 'Bornheim No3 High Velocity', cost: 50, unlock: 'Bornheim No. 3 Match' },
    { name: 'Bornheim No3 Incendiary', cost: 10, unlock: 'Bornheim No. 3' },
    { name: 'Caldwell Conversion DumDum', cost: 50, unlock: 'Caldwell Conversion Chain Pistol' },
    { name: 'Caldwell Conversion FMJ', cost: 50, unlock: 'Caldwell Conversion DumDum' },
    { name: 'Caldwell Conversion Uppercut Explosive', cost: 100, unlock: 'Caldwell Conversion Uppercut Incendiary' },
    { name: 'Caldwell Conversion Uppercut Incendiary', cost: 20, unlock: 'Caldwell Conversion Uppercut' },
    { name: 'Caldwell Pax DumDum', cost: 50, unlock: 'Caldwell Pax Claw' },
    { name: 'Caldwell Pax Incendiary', cost: 10, unlock: 'Caldwell Pax' },
    { name: 'Caldwell Rival 78 Flechette', cost: 40, unlock: 'Caldwell Rival 78' },
    { name: 'Caldwell Rival 78 Penny Shot', cost: 10, unlock: 'Caldwell Rival 78 Handcannon' },
    { name: 'Caldwell Rival 78 Slug', cost: 130, unlock: 'Caldwell Rival 78 Penny Shot' },
    { name: 'Crossbow Explosive Bolt', cost: 35, unlock: 'Hand Crossbow Choke Bolt' },
    { name: 'Crossbow Shot Bolt', cost: 40, unlock: 'Crossbow Explosive Bolt' },
    { name: 'Crown & King Auto-5 Penny Shot', cost: 10, unlock: 'Crown & King Auto-5' },
    { name: 'Crown & King Auto-5 Slug', cost: 130, unlock: 'Crown & King Auto-5 Penny Shot' },
    { name: 'Hand Crossbow Chaos Bolt', cost: 10, unlock: 'Crossbow' },
    { name: 'Hand Crossbow Choke Bolt', cost: 10, unlock: 'Hand Crossbow Chaos Bolt' },
    { name: 'Hand Crossbow Poison Bolt', cost: 25, unlock: 'Hand Crossbow' },
    { name: 'Hunting Bow Concertina Arrows', cost: 30, unlock: 'Hunting Bow Poison Arrows' },
    { name: 'Hunting Bow Frag Arrows', cost: 70, unlock: 'Hunting Bow Concertina Arrows' },
    { name: 'Hunting Bow Poison Arrows', cost: 25, unlock: 'Hunting Bow' },
    { name: 'LeMat Mark II Dragonbreath', cost: 10, unlock: 'LeMat Mark II Incendiary' },
    { name: 'LeMat Mark II FMJ', cost: 50, unlock: 'LeMat Mark II Dragonbreath' },
    { name: 'LeMat Mark II Incendiary', cost: 10, unlock: 'LeMat Mark II Starshell' },
    { name: 'LeMat Mark II Slug', cost: 65, unlock: 'LeMat Mark II FMJ' },
    { name: 'LeMat Mark II Starshell', cost: 5, unlock: 'LeMat Mark II Revolver' },
    { name: 'Lebel 1886 Incendiary', cost: 20, unlock: 'Lebel 1886' },
    { name: 'Lebel 1886 Spitzer', cost: 150, unlock: 'Lebel 1886 Marksman' },
    { name: 'Martini Henry IC1 Explosive', cost: 50, unlock: 'Martini Henry IC1 Marksman' },
    { name: 'Martini Henry IC1 FMJ', cost: 30, unlock: 'Martini Henry IC1 Deadeye' },
    { name: 'Martini Henry IC1 Incendiary', cost: 10, unlock: 'Martini Henry IC1' },
    { name: 'Mosin-Nagant M1891 Incendiary', cost: 20, unlock: 'Mosin-Nagant M1891 Obrez' },
    { name: 'Mosin-Nagant M1891 Spitzer', cost: 150, unlock: 'Mosin-Nagant M1891 Sniper' },
    { name: 'Nagant M1895 High Velocity', cost: 75, unlock: 'Nagant M1895 Poison' },
    { name: 'Nagant M1895 Officer High Velocity', cost: 50, unlock: 'Nagant M1895 Officer Carbine' },
    { name: 'Nagant M1895 Officer Poison', cost: 50, unlock: 'Nagant M1895 Officer Brawler' },
    { name: 'Nagant M1895 Poison', cost: 50, unlock: 'Nagant M1895 Deadeye' },
    { name: 'Nitro Express Rifle Shredder', cost: 225, unlock: 'Nitro Express Rifle' },
    { name: 'Nitro Express Rifle Explosive', cost: 200, unlock: 'Nitro Express Rifle Shredder' },
    { name: 'Romero 77 Dragonbreath', cost: 10, unlock: 'Romero 77 Starshell' },
    { name: 'Romero 77 Penny Shot', cost: 5, unlock: 'Romero 77 Talon' },
    { name: 'Romero 77 Slug', cost: 65, unlock: 'Romero 77 Hatchet' },
    { name: 'Romero 77 Starshell', cost: 5, unlock: 'Romero 77 Handcannon' },
    { name: 'Romero 77 Alamo Dragonbreath', cost: 20, unlock: 'Romero 77 Starshell' },
    { name: 'Romero 77 Alamo Penny Shot', cost: 10, unlock: 'Romero 77 Talon' },
    { name: 'Romero 77 Alamo Slug', cost: 130, unlock: 'Romero 77 Alamo' },
    { name: 'Romero 77 Alamo Starshell', cost: 10, unlock: 'Romero 77 Handcannon' },
    { name: 'Scottfield Model 3 FMJ', cost: 50, unlock: 'Scottfield Model 3 Brawler' },
    { name: 'Scottfield Model 3 Incendiary', cost: 10, unlock: 'Scottfield Model 3' },
    { name: 'Sparks LRR FMJ', cost: 30, unlock: 'Sparks LRR Sniper' },
    { name: 'Sparks LRR Incendiary', cost: 10, unlock: 'Sparks LRR' },
    { name: 'Sparks LRR Poison', cost: 30, unlock: 'Sparks LRR Silencer' },
    { name: 'Specter 1882 Dragonbreath', cost: 20, unlock: 'Specter 1882 Compact' },
    { name: 'Specter 1882 Flechette', cost: 40, unlock: 'Specter 1882' },
    { name: 'Specter 1882 Penny Shot', cost: 10, unlock: 'Specter 1882 Bayonet' },
    { name: 'Specter 1882 Slug', cost: 130, unlock: 'Specter 1882 Penny Shot' },
    { name: 'Springfield 1866 DumDum', cost: 25, unlock: 'Springfield 1866 Marksman' },
    { name: 'Springfield 1866 Explosive', cost: 45, unlock: 'Springfield 1866 Compact Deadeye' },
    { name: 'Standard Projectile', cost: 0, rank: 1 },
    { name: 'Vetterli 71 Karabiner FMJ', cost: 50, unlock: 'Vetterli 71 Karabiner Marksman' },
    { name: 'Vetterli 71 Karabiner High Velocity', cost: 50, unlock: 'Vetterli 71 Karabiner Silencer' },
    { name: 'Vetterli 71 Karabiner Incendiary', cost: 10, unlock: 'Vetterli 71 Karabiner Deadeye' },
    { name: 'Winfield 1887 Terminus Dragonbreath', cost: 20, unlock: 'Winfield 1887 Terminus Penny Shot' },
    { name: 'Winfield 1887 Terminus Flechette', cost: 40, unlock: 'Winfield 1887 Terminus' },
    { name: 'Winfield 1887 Terminus Penny Shot', cost: 10, unlock: 'Winfield 1887 Terminus Handcannon' },
    { name: 'Winfield 1887 Terminus Slug', cost: 130, unlock: 'Winfield 1887 Terminus Dragonbreath' },
    { name: 'Winfield M1873 High Velocity', cost: 50, unlock: 'Winfield M1873 Talon' },
    { name: 'Winfield M1873 Incendiary', cost: 10, unlock: 'Winfield M1873 Aperture' },
    { name: 'Winfield M1873 FMJ', cost: 50, unlock: 'Winfield M1873 Swift' },
    { name: 'Winfield M1873C High Velocity', cost: 50, unlock: 'Winfield M1873C Vandal' },
    { name: 'Winfield M1873C Incendiary', cost: 10, unlock: 'Winfield M1873C High Velocity' },
    { name: 'Winfield M1873C FMJ', cost: 50, unlock: 'Winfield M1873C Vandal Striker' },
    { name: 'Winfield M1876 Centennial FMJ', cost: 50, unlock: 'Winfield M1876 Centennial Poison' },
    { name: 'Winfield M1876 Centennial Poison', cost: 50, unlock: 'Winfield M1876 Centennial' },
    { name: 'Winfield 1893 Slate Penny Shot', cost: 10, unlock: 'Winfield 1893 Slate' },
    { name: 'Winfield 1893 Slate Slug', cost: 130, unlock: 'Winfield 1893 Slate Penny Shot' },
    { name: 'Berthier Mle 1892 Incendiary', cost: 10, unlock: 'Berthier Mle 1892' },
    { name: 'Berthier Mle 1892 Spitzer', cost: 75, unlock: 'Berthier Mle 1892 Deadeye' },
    { name: 'Caldwell 92 New Army DumDum', cost: 50, unlock: 'Caldwell 92 New Army' },
    { name: 'Caldwell 92 New Army FMJ', cost: 50, unlock: 'Caldwell 92 New Army DumDum' },
];
